---
fixtures:
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    vcsrepo: "puppetlabs/vcsrepo"
  repositories:
    deploy: "https://github.com/opus-codium/puppet-deploy.git"
  symlinks:
    bundle: "#{source_dir}"
